# KeyAuth Configuration
KEYAUTH_NAME = "YOUR_APPLICATION_NAME"
KEYAUTH_OWNERID = "YOUR_OWNER_ID"
KEYAUTH_SECRET = "YOUR_APPLICATION_SECRET"

# GUI Configuration
WINDOW_WIDTH = 400
WINDOW_HEIGHT = 500
WINDOW_TITLE = "Secure Loader"

# Colors
BACKGROUND_COLOR = "#1a1a1a"
ACCENT_COLOR = "#7289da"
SUCCESS_COLOR = "#43b581"
ERROR_COLOR = "#f04747"
TEXT_COLOR = "#ffffff" 